import React,{useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import {api} from "../api";
const money=n=>`₹${Number(n).toLocaleString("en-IN")}`;
export default function Checkout({cart,user,clearCart}){
 const nav=useNavigate(),[f,setF]=useState({name:user?.name||"",phone:"",address:"",city:"",pincode:""}),[method,setMethod]=useState("cod"),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0),shipping=subtotal>=1499?0:79,total=subtotal+shipping;
 if(!cart.length)return <main className="page empty-page"><h1>Your bag is empty.</h1><Link className="button dark" to="/shop">SHOP NOW</Link></main>;
 async function place(e){e.preventDefault();if(!user){nav("/account");return}setBusy(true);setErr("");try{const d=await api("/orders/create",{method:"POST",body:JSON.stringify({items:cart.map(i=>({productId:i.id,quantity:i.qty})),shipping:{...f,address:`${f.address}, ${f.city} - ${f.pincode}`},payment_method:method})});clearCart();nav("/success",{state:{order:d.order,paymentMethod:method}})}catch(x){setErr(x.message)}finally{setBusy(false)}}
 return <main className="page"><p className="eyebrow">SECURE CHECKOUT</p><h1>Complete your order.</h1><div className="checkout-grid"><form className="form-card" onSubmit={place}><h2>Delivery details</h2><input required placeholder="Full name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required pattern="[0-9]{10}" placeholder="10-digit phone number" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><textarea required rows="4" placeholder="House / street / area" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><div className="two-inputs"><input required placeholder="City" value={f.city} onChange={e=>setF({...f,city:e.target.value})}/><input required pattern="[0-9]{6}" placeholder="Pincode" value={f.pincode} onChange={e=>setF({...f,pincode:e.target.value})}/></div><h2>Payment</h2><label className="payment-option"><input type="radio" checked={method==="cod"} onChange={()=>setMethod("cod")}/><span><strong>Cash on Delivery</strong><small>Pay when your order arrives.</small></span></label><label className="payment-option disabled"><input type="radio" checked={method==="online"} onChange={()=>setMethod("online")}/><span><strong>Online payment</strong><small>Available when Razorpay is configured.</small></span></label>{method==="online"&&<p className="notice">Online payment requires your Razorpay keys on Render. For now, choose Cash on Delivery.</p>}{err&&<p className="error">{err}</p>}<button className="button dark full" disabled={busy||method==="online"}>{busy?"CREATING ORDER...":`PLACE ORDER · ${money(total)}`}</button></form><aside className="summary"><h2>Order summary</h2>{cart.map(i=><div className="summary-row" key={i.id}><span>{i.name} × {i.qty}</span><b>{money(i.price*i.qty)}</b></div>)}<div className="summary-row"><span>Shipping</span><b>{shipping?money(shipping):"FREE"}</b></div><hr/><div className="summary-total"><span>Total</span><b>{money(total)}</b></div><small>Free shipping on orders over ₹1,499.</small></aside></div></main>
}
